### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by eracknaphobia** [gagebenne/pydexcom#18]
I'm trying to debug a login issue I'm experiencing.

It seems that my account passes the `DEXCOM_AUTHENTICATE_ENDPOINT` which tells me my username and pwd are correct

![image](https://user-images.githubusercontent.com/8268725/145876512-3a9333d3-72e6-46a9-be1c-16d54aae8668.png)

However, I receive the `DEFAULT_SESSION_ID` for the `DEXCOM_LOGIN_ENDPOINT`. 
![image](https://user-images.githubusercontent.com/8268725/145876745-5edc5641-6e0e-4238-9577-965684c4ffd6.png)

Any Ideas? Seems like dexcom may have recently made some changes on their end. Should I just wait for the dust to settle and try later?

**Comment by gagebenne** [comment]
Are you a US user, or outside of the US?

**Comment by eracknaphobia** [comment]
US user

**Comment by gagebenne** [comment]
Yeah, this issue closely aligns with #17. One last question -- are you using an email address for your username? I am able to replicate your exact error, but only when I send an incorrect password. Could you ensure your password is alphanumeric?

Either way, this should fail more gracefully than it is with the endpoint changes. Thank you.

**Comment by eracknaphobia** [comment]
I'm using email address for the username and the password is alphanumeric.

I do get the `DEFAULT_SESSION_ID` if i purposely send the incorrect password in the `DEXCOM_LOGIN_ENDPOINT`, but with the  `DEXCOM_AUTHENTICATE_ENDPIONT` I get it no matter what.

Thanks for the quick response!

**Comment by gagebenne** [comment]
When you go to your Dexcom G6 application, what do you see under Settings > Account > Username? Is it an email?

**Comment by eracknaphobia** [comment]
No problem at all. In the app the username is the email address.

**Comment by gagebenne** [comment]
Fixed. Please use `pydexcom==0.2.2`! Let me know if you have any more issues!

**Comment by eracknaphobia** [comment]
![image](https://user-images.githubusercontent.com/8268725/146553881-83fee3bb-c3c0-4e42-a329-b9d44e972546.png)

Still getting the all 0's UID with the new call.

**Comment by gagebenne** [comment]
Sorry, I never got around to releasing 0.2.2 to pypi, I'll do that around
lunch time, after that you should be set.

**Comment by eracknaphobia** [comment]
![image](https://user-images.githubusercontent.com/8268725/146557484-ecfd9aa5-6589-4e43-9ae0-47b725ecf2ff.png)
I manually updated the files and it worked! Thanks for fixing this so quickly @gagebenne!

As far as Home Assistant is concerned will these changes be pulled in automatically or will we need to wait for a version bump?

**Comment by gagebenne** [comment]
Nice! Glad to hear. I think it'll have to wait for a version bump unfortunately, here's the [pull request](https://github.com/home-assistant/core/pull/62207).

**Comment by eracknaphobia** [comment]
Ok, sounds good. Thanks again!
